CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  employee_code VARCHAR(255) UNIQUE,
  role VARCHAR(255) NOT NULL,
  department VARCHAR(255),
  designation VARCHAR(255),
  phone VARCHAR(255),
  joining_date VARCHAR(255),
  manager_name VARCHAR(255),
  password_hash VARCHAR(255) NOT NULL,
  casual_leave DOUBLE,
  sick_leave DOUBLE,
  earned_leave DOUBLE
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  work_date DATE,
  status VARCHAR(255),
  check_in VARCHAR(255),
  check_out VARCHAR(255),
  hours DOUBLE,
  shortfall DOUBLE,
  overtime DOUBLE
);

CREATE TABLE IF NOT EXISTS leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  type VARCHAR(255),
  start_date DATE,
  end_date DATE,
  duration VARCHAR(255),
  session VARCHAR(255),
  reason VARCHAR(1000),
  status VARCHAR(255),
  manager_comment VARCHAR(255),
  action_date DATE
);

CREATE TABLE IF NOT EXISTS daily_statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  status_date DATE,
  work_done VARCHAR(4000),
  blockers VARCHAR(2000),
  tomorrow_plan VARCHAR(2000),
  CONSTRAINT uk_daily_status_user_date UNIQUE (user_id, status_date)
);

CREATE TABLE IF NOT EXISTS payslips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  payslip_month VARCHAR(255),
  basic_salary DOUBLE,
  hra DOUBLE,
  allowances DOUBLE,
  pf DOUBLE,
  tax DOUBLE,
  net_salary DOUBLE,
  published_on VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255),
  message VARCHAR(2000),
  published_on DATE,
  category VARCHAR(255)
);
