package com.employeeportal.controller;
import com.employeeportal.model.User; import com.employeeportal.repo.UserRepository; import com.employeeportal.security.JwtService; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/auth") public class AuthController{
 final UserRepository users; final PasswordEncoder encoder; final JwtService jwt; public AuthController(UserRepository u,PasswordEncoder e,JwtService j){users=u;encoder=e;jwt=j;}
 public record LoginRequest(@Email String email,@NotBlank String password){} public record SignupRequest(@Email String email,@NotBlank String password,@NotBlank String name,String department,String designation){}
 Map<String,Object> safe(User u){return Map.of("id",u.getId(),"email",u.getEmail(),"name",u.getName(),"employeeCode",u.getEmployeeCode(),"role",u.getRole(),"department",u.getDepartment(),"designation",u.getDesignation(),"managerName",u.getManagerName());}
 @PostMapping("/login") public ResponseEntity<?> login(@RequestBody LoginRequest r){User u=users.findByEmail(r.email()).orElse(null);if(u==null||!encoder.matches(r.password(),u.getPasswordHash()))return ResponseEntity.status(401).body(Map.of("message","Invalid email or password"));return ResponseEntity.ok(Map.of("token",jwt.create(u.getId(),u.getEmail(),u.getRole()),"user",safe(u)));}
 @PostMapping("/signup") public ResponseEntity<?> signup(@RequestBody SignupRequest r){if(users.findByEmail(r.email()).isPresent())return ResponseEntity.badRequest().body(Map.of("message","Email already registered"));String code="EMP-"+String.format("%03d",users.count());User u=new User(null,r.email(),r.name(),code,"EMPLOYEE",r.department(),r.designation(),encoder.encode(r.password()),"Neeraj Mehta");users.save(u);return ResponseEntity.status(201).body(Map.of("message","Account created successfully"));}
}
