package com.employeeportal.controller;
import com.employeeportal.model.*; import com.employeeportal.repo.*; import org.springframework.web.bind.annotation.*; import org.springframework.http.*; import org.springframework.security.core.context.SecurityContextHolder; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api") public class PortalController{
 final UserRepository users; final LeaveRepository leaves; final AttendanceRepository attendance; final AnnouncementRepository announcements; final DailyStatusRepository statuses; final PayslipRepository payslips;
 PortalController(UserRepository u,LeaveRepository l,AttendanceRepository a,AnnouncementRepository n,DailyStatusRepository s,PayslipRepository p){users=u;leaves=l;attendance=a;announcements=n;statuses=s;payslips=p;}
 User current(){return users.findByEmail(SecurityContextHolder.getContext().getAuthentication().getName()).orElseThrow();}
 Map<String,Object> safe(User u){Map<String,Object> m=new LinkedHashMap<>();m.put("id",u.getId());m.put("email",u.getEmail());m.put("name",u.getName());m.put("employeeCode",u.getEmployeeCode());m.put("role",u.getRole());m.put("department",u.getDepartment());m.put("designation",u.getDesignation());m.put("managerName",u.getManagerName());m.put("phone",u.getPhone());m.put("joiningDate",u.getJoiningDate());m.put("casualLeave",u.getCasualLeave());m.put("sickLeave",u.getSickLeave());m.put("earnedLeave",u.getEarnedLeave());return m;}
 @GetMapping("/me") Map<String,Object> me(){return safe(current());}
 @GetMapping("/dashboard") Map<String,Object> dashboard(){User u=current();var at=attendance.findByUserIdOrderByWorkDateDesc(u.getId());var ls=leaves.findByUserIdOrderByStartDateDesc(u.getId());var ds=statuses.findByUserIdOrderByStatusDateDesc(u.getId());long approved=ls.stream().filter(x->"APPROVED".equals(x.getStatus())).count();double shortfall=at.stream().mapToDouble(Attendance::getShortfall).sum();double overtime=at.stream().mapToDouble(Attendance::getOvertime).sum();double worked=at.stream().mapToDouble(a->a.getHours()==null?0:a.getHours()).sum();Map<String,Object> out=new LinkedHashMap<>();out.put("user",safe(u));out.put("attendance",at);out.put("leaveRequests",ls);out.put("dailyStatuses",ds);out.put("payslips",payslips.findByUserIdOrderByMonthDesc(u.getId()));out.put("announcements",announcements.findAllByOrderByPublishedOnDesc());out.put("approvedLeaves",approved);out.put("leaveBalance",(u.getCasualLeave()+u.getSickLeave()+u.getEarnedLeave()-approved));out.put("shortfallHours",shortfall);out.put("overtimeHours",overtime);out.put("workedHours",worked);return out;}
 @GetMapping("/attendance") List<Attendance> myAttendance(){return attendance.findByUserIdOrderByWorkDateDesc(current().getId());}
 @GetMapping("/leaves") List<LeaveRequest> myLeaves(){return leaves.findByUserIdOrderByStartDateDesc(current().getId());}
 @PostMapping("/leaves") LeaveRequest createLeave(@RequestBody LeaveRequest r){return leaves.save(new LeaveRequest(null,current().getId(),r.getType(),r.getStartDate(),r.getEndDate(),r.getDuration(),r.getSession(),r.getReason(),"PENDING"));}
 @GetMapping("/daily-status") List<DailyStatus> myStatuses(){return statuses.findByUserIdOrderByStatusDateDesc(current().getId());}
 @PostMapping("/daily-status") ResponseEntity<?> saveStatus(@RequestBody DailyStatus r){User u=current();LocalDate d=r.getStatusDate()==null?LocalDate.now():r.getStatusDate();if(d.isAfter(LocalDate.now()))return ResponseEntity.badRequest().body(Map.of("message","Status date cannot be in the future"));DailyStatus s=statuses.findByUserIdAndStatusDate(u.getId(),d).orElse(new DailyStatus(null,u.getId(),d,"","",""));s.setWorkDone(r.getWorkDone());s.setBlockers(r.getBlockers());s.setTomorrowPlan(r.getTomorrowPlan());return ResponseEntity.ok(statuses.save(s));}
 @GetMapping("/payslips") List<Payslip> myPayslips(){return payslips.findByUserIdOrderByMonthDesc(current().getId());}
 @GetMapping("/announcements") List<Announcement> anns(){return announcements.findAllByOrderByPublishedOnDesc();}
 @PutMapping("/profile") Map<String,Object> profile(@RequestBody Map<String,String> b){User u=current();if(b.containsKey("name"))u.setName(b.get("name"));if(b.containsKey("phone"))u.setPhone(b.get("phone"));users.save(u);return safe(u);}
}
